name: Pipeline

on:
  push:
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:


  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: HTML5
            path: ./dist/html5/index.html
            name: HTML5
            upload: godot/dist/html5/*


    steps:

      - uses: actions/checkout@v3

      - run: mkdir -p godot/"$(dirname '${{ matrix.path }}')"

      - run: docker build -t ghcr.io/bcorfman/godot/export container

      - run: >-
          docker run --rm
          -v $(pwd):/wrk -w /wrk/godot
          ghcr.io/bcorfman/godot/export
          gexport --export-release '${{ matrix.preset }}' '${{ matrix.path }}'

      - name: '📤 Upload artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.upload }}
          if-no-files-found: error


  pages:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: '📥 Download artifacts: doc'
        uses: actions/download-artifact@v3
        with:
          name: doc
          path: public

      - name: '📥 Download artifacts: HTML5'
        uses: actions/download-artifact@v3
        with:
          name: HTML5
          path: public/play

      - run: tree public

      # Workaround for SharedArrayBuffer support on GitHub Pages
      # See: https://github.com/godotengine/godot-docs/issues/7084
      - run: |
          cd public/play
          curl -fsSL https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.js > coi-serviceworker.js
          sed -i 's#\(		<script src="index.js"></script>\)#		<script src="coi-serviceworker.js"></script>\n\1#g' index.html

      - name: 🚀 Publish to GitHub Pages
        if: (github.event_name != 'pull_request')
        run: |
          cd public
          touch .nojekyll
          git init
          cp ../.git/config ./.git/config
          git add .
          git config --local user.email "godot@GitHubActions"
          git config --local user.name "GitHub Actions"
          git commit -a -m "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
