name: Pipeline

on:
  push:
  pull_request:

jobs:
  make-container:
    name: Make Docker container with Godot
    runs-on: ubuntu-latest

    permissions:
      packages: write
    
    steps:
      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code from git
        uses: actions/checkout@v3
      - name: Build and push to GHCR
        run: |
          docker build -t ghcr.io/${{ github.actor }}/godot/export container 
          docker push ghcr.io/${{ github.actor }}/godot/export
  
  build:
    name: Build Godot game as Web version
    needs: [make-container]
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: make HTML directory
        run: mkdir -p godot/"$(dirname .dist/html5/index.html)"
      - name: Export game to web version
        uses: docker://ghcr.io/bcorfman/godot/export:latest
        env:
          GODOT_EXPORT_SUBDIR: godot
        with:
          args: gexport --export-release HTML5 ./dist/html5/index.html
      - name: '📤 Upload artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: HTML5
          path: godot/dist/html5/*
          if-no-files-found: error


  pages:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: '📥 Download artifacts: HTML5'
        uses: actions/download-artifact@v3
        with:
          name: HTML5
          path: public/play

      - run: tree public

      # Workaround for SharedArrayBuffer support on GitHub Pages
      # See: https://github.com/godotengine/godot-docs/issues/7084
      - run: |
          cd public/play
          curl -fsSL https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.js > coi-serviceworker.js
          sed -i 's#\(		<script src="index.js"></script>\)#		<script src="coi-serviceworker.js"></script>\n\1#g' index.html

      - name: 🚀 Publish to GitHub Pages
        if: (github.event_name != 'pull_request')
        run: |
          cd public
          touch .nojekyll
          git init
          cp ../.git/config ./.git/config
          git add .
          git config --local user.email "godot@GitHubActions"
          git config --local user.name "GitHub Actions"
          git commit -a -m "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
