name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  make-container:
    name: Make Docker container with Godot
    runs-on: ubuntu-latest

    permissions:
      packages: write
    
    steps:
      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Checkout code from git
        uses: actions/checkout@v3
      - name: Build and push to GHCR
        run: |
          docker build -t ghcr.io/${{ github.actor }}/godot/export container 
          docker push ghcr.io/${{ github.actor }}/godot/export
  
  build:
    name: Build Godot game as Web version
    needs: [make-container]
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Login to ghcr.io registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: make web directory
        run: mkdir -p godot/dist/web
      - name: Export game to web version
        uses: docker://ghcr.io/bcorfman/godot/export:latest
        env:
          GODOT_EXPORT_SUBDIR: godot
        with:
          args: gexport --export-release Web ./dist/web/index.html
      - name: '📤 Upload artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: Web
          path: godot/dist/web/*
          if-no-files-found: error


  pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: godot/dist/web
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}