# https://github.com/seanmaxwell/godot-example-auto-deploy/blob/main/.github/workflows/godot-ci.yml

name: Deploy game
on: 
  push:
    tags:
      - 'v*'

env:
  GAME_NAME: alien_attack_supreme
  PROJECT_PATH: "./godot/"
  EXPORT_PATH: "./builds"
  GODOT_VERSION: "4.0.2"

jobs:
  export-game:
    name: Export game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Export
        id: export
        uses: firebelley/godot-export@v5.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}-stable_export_templates.tpz
          relative_project_path: ${{ env.PROJECT_PATH}}
          use_preset_export_path: false
          relative_export_path: ${{ env.EXPORT_PATH }}
          archive_output: true
      #- name: Upload Windows Artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.windows
      #    path: ${{ steps.export.outputs.archive_directory }}/Windows
      #- name: Upload MacOS Artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.mac
      #    path: ${{ steps.export.outputs.archive_directory }}/Mac
      #- name: Upload Linux Artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.linux
      #    path: ${{ steps.export.outputs.archive_directory }}/Linux
      #- name: Upload Web Artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.web
      #    path: ${{ steps.export.outputs.archive_directory }}/Web
      #- name: Deploy to GitHub Pages
      #  if: success() 
      #  uses: crazy-max/ghaction-github-pages@v3
      #  with:
      #    target_branch: gh-pages
      #    build_dir: ${{ steps.export.outputs.archive_directory }}/Web
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: create release
        uses: ncipollo/release-action@v1.11.2
        with:
          token: ${{ secrets.PAT }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/* # Added "/*" at the end is glob pattern match for this action
  
  pages-deploy:
    name: Deploy to GitHub Pages
    needs: export-game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifact (web)
        uses: actions/download-artifact@v3
        with:
          name: Web.zip
          path: builds/web
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: builds/web
