# https://github.com/seanmaxwell/godot-example-auto-deploy/blob/main/.github/workflows/godot-ci.yml

name: Deploy game
on: push

env:
  GAME_NAME: alien_attack_supreme
  PROJECT_PATH: "./godot/"
  GODOT_VERSION: "4.0.2"

jobs:
  export-game:
    name: Export game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Export
        id: export
        uses: firebelley/godot-export@v5.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{env.GODOT_VERSION}}/Godot_v${{env.GODOT_VERSION}}-stable_export_templates.tpz
          relative_project_path: ${{ env.PROJECT_PATH}}
          use_godot_4: true
          use_preset_export_path: true
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.windows
          path: ${{ steps.export.outputs.build_directory }}/Windows Desktop
      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.mac
          path: ${{ steps.export.outputs.build_directory }}/macOS
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.linux
          path: ${{ steps.export.outputs.build_directory }}/LinuxX11
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.web
          path: ${{ steps.export.outputs.build_directory }}/Web
      - name: Deploy to GitHub Pages
        if: success() 
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ${{ steps.export.outputs.build_directory }}/Web
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
