name: Godot-CI Export

on:
  push:

env:
  GODOT_VERSION: 4.0.2
  EXPORT_NAME: alien_attack_supreme

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: docker://aorioli/godot-ci:4.0.2
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p build/linux build/windows build/mac build/web ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          mv "/root/.local/share/godot/export_templates/$(GODOT_VERSION).stable" "~/.local/share/godot/export_templates/$(GODOT_VERSION).stable"
      - name: Windows Build
        run: godot -v --path godot --headless --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
      - name: '📤 Upload artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: Windows
          path: ./build/windows/*
          if-no-files-found: error

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: docker://aorioli/godot-ci:4.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p build/linux build/windows build/mac build/web ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable
          mv /root/.local/share/godot/export_templates/$GODOT_VERSION.stable ~/.local/share/godot/export_templates/$GODOT_VERSION.stable
      - name: Linux Build
        run: godot -v --path godot --headless --export-release "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
      - name: '📤 Upload artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: Linux
          path: ./build/linux/*
          if-no-files-found: error
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: docker://aorioli/godot-ci:4.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p build/linux build/windows build/mac build/web ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable
          mv /root/.local/share/godot/export_templates/$GODOT_VERSION.stable ~/.local/share/godot/export_templates/$GODOT_VERSION.stable
      - name: Web Build
        run: godot -v --path godot --headless --export-release "Web" ./build/web/index.html
      #- name: "Workaround for SharedArrayBuffer support on GitHub Pages"
      #  run: |
      #    cd build/web
      #    ls -l
      #    wget -nv -o coi-serviceworker.js https://github.com/gzuidhof/coi-serviceworker/raw/master/coi-serviceworker.js 
      #    sed -i 's#\(		<script src="index.js"></script>\)#		<script src="coi-serviceworker.js"></script>\n\1#g' index.html
      #    cd ../..
      - name: '📤 Upload artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: Web
          path: ./build/web/*
          if-no-files-found: error
      - name: Deploy to GitHub Pages
        if: success() 
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./build/web
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: docker://aorioli/godot-ci:4.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p build/linux build/windows build/mac build/web ~/.local/share/godot/templates ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/$GODOT_VERSION.stable ~/.local/share/godot/templates/$GODOT_VERSION.stable
          mv /root/.local/share/godot/export_templates/$GODOT_VERSION.stable ~/.local/share/godot/export_templates/$GODOT_VERSION.stable
      - name: Mac Build
        run: godot -v --path godot --headless --export-release "MacOS" ./build/mac/$EXPORT_NAME.zip
      - name: '📤 Upload artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: Mac
          path: ./build/mac/*
          if-no-files-found: error
